import {stateFromLoad} from './state-loader.mjs';
import {saveSettings} from './settings-transaction.mjs';
import {createState,applyCommand,validateState,recoverState,makeDeadline,groups,elapsed,formatElapsed} from '../core/model.mjs';
import {HostBridge} from './bridge.mjs';
import {translator,localeFor} from './i18n.mjs';
import {notificationFor} from './notification-policy.mjs';
const $=selector=>document.querySelector(selector), $$=selector=>[...document.querySelectorAll(selector)];
const host=new HostBridge();
const quick=new URLSearchParams(location.search).get('view')==='quick';
let clockOffset=0;
const mono=()=>clockOffset+performance.now();
function syncClock(result){if(Number.isFinite(result.monotonicMs))clockOffset=result.monotonicMs-performance.now();}
function assertState(value){const result=validateState(value);if(!result.valid)throw new Error(result.error);}
const context=()=>({now:Date.now(),monotonic:mono(),timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone});
let state=null,revision=0,busy=false,ready=false,native={},latestExternal=null;
let t=translator('ru'),locale='ru-RU',editorId=null,editorZone=null,collectionType='archive';
let menuTrigger=null,menuId=null,lastFocus=null,lastTheme=null,retryAction=null;
let undoHover=false,nativeVisible=true,lastUndo=mono(),lastTick=0,lastCheckpoint=mono();
const systemTheme=matchMedia('(prefers-color-scheme: dark)');
document.body.classList.toggle('quick',quick);
function text(node,value){node.textContent=value;return node;}
function element(tag,className,value){const node=document.createElement(tag);if(className)node.className=className;if(value!==undefined)text(node,value);return node;}
function icon(name){const node=document.createElementNS('http://www.w3.org/2000/svg','svg');node.setAttribute('aria-hidden','true');const use=document.createElementNS(node.namespaceURI,'use');use.setAttribute('href',`#i-${name}`);node.append(use);return node;}
function button(className,label,handler,iconName){const node=element('button',className);node.type='button';node.setAttribute('aria-label',label);node.title=label;if(iconName)node.append(icon(iconName));else text(node,label);if(handler)node.addEventListener('click',handler);return node;}
function report(error,action=null,target=$('#error')){retryAction=action;const damaged=/dataCorrupt|invalidState/.test(String(error?.message||error));$('#restore-backup').hidden=!damaged;const key=damaged?'dataCorrupt':/hotkey|Repeated modifier/i.test(String(error?.message||error))?'hotkeyError':['nativeRollbackError','noHost','conflict','invalidDate','nativeError'].find(k=>String(error?.message||error).includes(k))||'saveError';if(target===$('#error')){text($('#error-text'),t(key));$('#retry').hidden=!action;target.hidden=false;}else{text(target,t(key));target.hidden=false;}}
function clearError(){ $('#error').hidden=true;$('#restore-backup').hidden=true;retryAction=null; }
function announce(value){text($('#status'),value);}
function setBusy(value){busy=value;$('#add-task').disabled=!ready||busy||!$('#task-input').value.trim();$('#editor-save').disabled=busy;$('#settings-form .save').disabled=busy;$('#widget').setAttribute('aria-busy',String(value));}
// Collapsed groups live only in the UI layer: persisting them would mean touching the
// stored schema, which carries its own version and tests. localStorage is per-window
// and may be unavailable, so every access is guarded and a failure just means the
// groups reopen next launch.
const collapsedGroups=new Set((()=>{try{return JSON.parse(localStorage.getItem('delo.collapsedGroups'))||[];}catch{return [];}})());
function persistCollapsed(){try{localStorage.setItem('delo.collapsedGroups',JSON.stringify([...collapsedGroups]));}catch{}}
function toggleGroup(key,section,toggle){const next=!section.classList.contains('collapsed');section.classList.toggle('collapsed',next);toggle.setAttribute('aria-expanded',String(!next));if(next)collapsedGroups.add(key);else collapsedGroups.delete(key);persistCollapsed();}
function localize(){t=translator(state?.settings.language);locale=localeFor(state?.settings.language);document.documentElement.lang=state?.settings.language||'ru';$$('[data-text]').forEach(node=>text(node,t(node.dataset.text)));$$('[data-label]').forEach(node=>{node.setAttribute('aria-label',t(node.dataset.label));node.title=t(node.dataset.label);});$$('[data-placeholder]').forEach(node=>node.placeholder=t(node.dataset.placeholder));applyTheme();}
function applyTheme(){const theme=state?.settings.theme||'system',dark=theme==='dark'||(theme==='system'&&systemTheme.matches);document.body.classList.toggle('dark',dark);document.body.classList.toggle('reduced',!!state?.settings.reducedMotion);if(dark!==lastTheme){lastTheme=dark;host.window('theme',{dark}).catch(()=>{});}}
systemTheme.addEventListener('change',applyTheme);
function dateText(task){if(!task.due)return t('dueNone');const due=task.due;let value=new Intl.DateTimeFormat(locale,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${due.date}T12:00:00Z`));if(due.time)value+=` · ${due.time}`;if(due.timeZone!==context().timeZone)value+=` · ${due.timeZone}`;return value;}
function animate(node,frames,duration=220){if(!document.body.classList.contains('reduced')&&!matchMedia('(prefers-reduced-motion: reduce)').matches)node.animate(frames,{duration,easing:'cubic-bezier(.2,.8,.2,1)'});}
// Own tone, not MessageBeep: the stock Windows alert belongs to the OS, not to this
// widget, and it reads as an error even on completion. Two short sine notes rising for
// a finished task, falling for an overdue one.
let audioContext;
function tone(steps){
  try{
    audioContext??=new (globalThis.AudioContext||globalThis.webkitAudioContext)();
    audioContext.resume().catch(()=>{});
    const start=audioContext.currentTime;
    steps.forEach(([frequency,delay],index)=>{
      const osc=audioContext.createOscillator(),gain=audioContext.createGain();
      osc.type='sine';osc.frequency.value=frequency;
      const at=start+delay;
      gain.gain.setValueAtTime(0,at);
      gain.gain.linearRampToValueAtTime(index?.028:.035,at+.015);
      gain.gain.exponentialRampToValueAtTime(.001,at+.27);
      osc.connect(gain);gain.connect(audioContext.destination);
      osc.start(at);osc.stop(at+.3);
      osc.onended=()=>{osc.disconnect();gain.disconnect();};
    });
  }catch{}
}
function play(kind){
  if(!state?.settings[kind==='complete'?'completionSound':'overdueSound'])return;
  tone(kind==='complete'?[[660,0],[880,.07]]:[[520,0],[392,.09]]);
}
async function load({startup=false}={}){const result=await host.request('load');syncClock(result);state=stateFromLoad(result);revision=result.revision??0;native=result.native??native;ready=true;localize();render();if(startup&&!quick){const recovered=recoverState(state);if(JSON.stringify(recovered)!==JSON.stringify(state))await commitState(recovered);await mutate({type:'tick'},{silent:true});}setBusy(false);if(native.hotkeyError)report(Error(native.hotkeyError));return state;}
async function commitState(candidate){const sentRevision=revision;const result=await host.request('save',{state:candidate,revision:sentRevision});state=candidate;revision=result?.revision??sentRevision+1;if(latestExternal&&latestExternal.revision>revision){state=latestExternal.state;revision=latestExternal.revision;}latestExternal=null;render();return true;}
async function transaction(commands,{silent=false,errorTarget=null,notifyOverdue=false}={}){if(busy||!ready)return false;setBusy(true);const before=state;try{syncClock(await host.request('clock'));let candidate=state;for(const command of commands)candidate=applyCommand(candidate,command,context());if(JSON.stringify(candidate)===JSON.stringify(state))return true;await commitState(candidate);if(!silent){clearError();announce(t('saved'));}const notification=notificationFor(before,state,commands,{notifyOverdue});if(notification)play(notification);return true;}catch(error){if(String(error.message).includes('conflict')){try{await load();}catch{ready=false;}}report(error,()=>transaction(commands,{silent,errorTarget,notifyOverdue}),errorTarget||$('#error'));return false;}finally{setBusy(false);if(latestExternal){state=latestExternal.state;revision=latestExternal.revision;latestExternal=null;localize();render();}}}
const mutate=(command,options)=>transaction([command],options);
function render(){if(!state)return;const active=$(':focus');const focusedTask=active?.closest('[data-task]')?.dataset.task;const focusedAction=active?.dataset.action;const previous=new Map($$('.task[data-task]').map(node=>[node.dataset.task,node.getBoundingClientRect().top]));const scroll=$('#task-scroll').scrollTop;localize();text($('#today'),new Intl.DateTimeFormat(locale,{weekday:'long',day:'numeric',month:'long'}).format(new Date()));text($('#score'),String(state.reputation));const pinned=native.pinned??state.settings.pinned;$('#pin').setAttribute('aria-pressed',String(pinned));$('#pin').title=t(pinned?'unpin':'pin');$('#pin').setAttribute('aria-label',$('#pin').title);if(!quick){const fragment=document.createDocumentFragment();for(const group of groups(state,context())){if(!group.tasks.length)continue;const section=element('section','task-group');section.dataset.group=group.key;const collapsed=collapsedGroups.has(group.key);if(collapsed)section.classList.add('collapsed');const heading=element('h2',`${group.key}-label`);const toggle=element('button','group-toggle');toggle.type='button';toggle.setAttribute('aria-expanded',String(!collapsed));toggle.append(icon('chevron'),element('span','group-name',t(group.key)),element('span','',String(group.tasks.length)));toggle.addEventListener('click',()=>toggleGroup(group.key,section,toggle));heading.append(toggle);section.append(heading);for(const task of group.tasks)section.append(taskRow(task,group.key));fragment.append(section);}if(!fragment.childNodes.length)fragment.append(element('p','empty',t('empty')));$('#task-scroll').replaceChildren(fragment);$('#task-scroll').scrollTop=scroll;for(const node of $$('.task[data-task]')){const old=previous.get(node.dataset.task);if(old===undefined)animate(node,[{opacity:0,transform:'translateY(6px)'},{opacity:1,transform:'none'}]);else{const delta=Math.max(-60,Math.min(60,old-node.getBoundingClientRect().top));if(Math.abs(delta)>1)animate(node,[{transform:`translateY(${delta}px)`},{transform:'none'}],260);}}if(focusedTask&&focusedAction){const replacement=$$('.task[data-task]').find(n=>n.dataset.task===focusedTask)?.querySelector(`[data-action="${focusedAction}"]`);replacement?.focus({preventScroll:true});}renderUndo();if($('#collection').open)renderCollection();if($('#history').open)renderHistory();}setBusy(busy);}
function taskRow(task,key){const row=element('article',`task ${key==='late'?'late ':''}${task.completedAt!==null?'done ':''}${['running','paused','working'].includes(task.workState)?'in-work':''}`);row.dataset.task=task.id;const completed=task.completedAt!==null;const check=button('complete',t(completed?'uncomplete':'complete'),()=>mutate({type:completed?'uncomplete':'complete',id:task.id}));check.dataset.action='complete';check.setAttribute('aria-pressed',String(completed));const circle=element('span','circle');circle.append(icon('check'));check.replaceChildren(circle);const copy=element('div','task-copy');const title=button('task-title',task.title,()=>openEditor(task));title.dataset.action='edit';const due=button('deadline',completed?`${t('completed')} · ${dateText(task)}`:dateText(task),()=>openEditor(task,true));due.dataset.action='date';copy.append(title,due);const actions=element('div','task-actions');const timer=button('timer',t(task.workState==='running'?'pause':'start'),()=>mutate({type:task.workState==='running'?'pause':'start',id:task.id}),task.workState==='running'?'pause':'play');timer.dataset.action='timer';timer.disabled=completed;timer.setAttribute('aria-pressed',String(task.workState==='running'));const more=button('task-more',t('actions'),event=>openMenu(task,event.currentTarget),'more');more.dataset.action='more';more.setAttribute('aria-haspopup','menu');more.setAttribute('aria-expanded',String(menuId===task.id));actions.append(timer,more);row.append(check,copy,actions);if(task.elapsedMs>0||task.workState!=='idle'){const strip=element('div','work-strip');strip.append(element('span','work-status',t(completed?'completed':task.workState)),element('span','elapsed',formatElapsed(elapsed(task,mono()))));if(!completed&&task.workState!=='idle'){const stop=button('stop-work',t('stop'),()=>mutate({type:'stop',id:task.id}),'stop');stop.dataset.action='stop';strip.append(stop);}row.append(strip);}return row;}
function updateTimes(){for(const row of $$('.task[data-task]')){const task=state.tasks.find(task=>task.id===row.dataset.task);const node=row.querySelector('.elapsed');if(node&&task)text(node,formatElapsed(elapsed(task,mono())));}}
function pendingTasks(){return state?.tasks.filter(task=>task.lifecycle==='pending').sort((a,b)=>a.deletedAt-b.deletedAt)||[];}
function undoPaused(){return undoHover||$('#undo-bar').contains(document.activeElement)||document.hidden||!nativeVisible;}
function renderUndo(){const tasks=pendingTasks(),task=tasks.at(-1);$('#undo-bar').hidden=!task;if(!task)return;text($('#undo-text'),task.title);text($('#undo-hint'),`${t(undoPaused()?'undoPaused':'undoHint')}${tasks.length>1?` · +${tasks.length-1} ${t('moreDeleted')}`:''}`);const remaining=Math.max(0,task.undoRemaining);text($('#undo-seconds'),undoPaused()?'Ⅱ':String(Math.max(1,Math.ceil(remaining/1000))));$('#undo-arc').style.strokeDashoffset=String(100-remaining/5000*100);}
function openDialog(dialog){closeMenu();lastFocus=document.activeElement;dialog.showModal();}
function closeDialog(dialog){dialog.close();lastFocus?.focus({preventScroll:true});}
$$('[data-close]').forEach(node=>node.addEventListener('click',()=>closeDialog(node.closest('dialog'))));$$('dialog').forEach(dialog=>dialog.addEventListener('cancel',()=>{lastFocus?.focus({preventScroll:true});}));
function openEditor(task=null,dateFocus=false){editorId=task?.id??null;editorZone=task?.due?.timeZone??context().timeZone;text($('#editor-title'),t(task?'edit':'newTask'));$('#editor-input').value=task?.title??$('#task-input').value;$('#due-input').value=task?.due?.date??'';$('#time-input').value=task?.due?.time??'';$('#editor-error').hidden=true;updateDateControls();openDialog($('#editor'));(dateFocus?$('#due-input'):$('#editor-input')).focus();grow($('#editor-input'));}
function updateDateControls(){if(!$('#due-input').value)$('#time-input').value='';text($('#zone-hint'),`${t('deadlineZone')}: ${editorZone||context().timeZone}`);const selected=$('#due-input').value;$$('[data-days]').forEach(button=>button.setAttribute('aria-pressed',String(selected===dateAfter(Number(button.dataset.days)))));$('#clear-date').setAttribute('aria-pressed',String(!selected));}
function dateAfter(days){const now=new Date();now.setDate(now.getDate()+days);return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;}
$$('[data-days]').forEach(node=>node.addEventListener('click',()=>{$('#due-input').value=dateAfter(Number(node.dataset.days));editorZone=context().timeZone;updateDateControls();}));$('#clear-date').addEventListener('click',()=>{$('#due-input').value='';updateDateControls();});$('#due-input').addEventListener('input',updateDateControls);
$('#editor-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const title=$('#editor-input').value.trim();if(!title)return;let due=null;try{if(!$('#due-input').checkValidity()||!$('#time-input').checkValidity()||($('#time-input').value&&!$('#due-input').value))throw Error();due=$('#due-input').value?makeDeadline($('#due-input').value,$('#time-input').value,editorZone):null;}catch{report(Error('invalidDate'),null,$('#editor-error'));return;}const commands=editorId?[{type:'edit',id:editorId,title},{type:'deadline',id:editorId,due}]:[{type:'create',id:crypto.randomUUID(),title,due}];if(await transaction(commands,{errorTarget:$('#editor-error')})){if(!editorId){$('#task-input').value='';grow($('#task-input'));}closeDialog($('#editor'));}});
function grow(input){input.style.height='auto';input.style.height=`${Math.min(input.scrollHeight,input.id==='editor-input'?180:quick?125:92)}px`;}
for(const input of [$('#task-input'),$('#editor-input')]){input.addEventListener('input',()=>{grow(input);setBusy(busy);});input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing&&event.keyCode!==229){event.preventDefault();if(!busy)input.closest('form').requestSubmit();}});}
async function submitEntry(){if(busy||!ready)return;const input=$('#task-input'),title=input.value.trim();if(!title)return;const original=input.value;const success=await mutate({type:'create',id:crypto.randomUUID(),title});if(success){if(input.value===original)input.value='';grow(input);setBusy(false);if(quick)await host.window('quickDone').catch(error=>report(error));else input.focus();}}
$('#entry').addEventListener('submit',event=>{event.preventDefault();submitEntry();});$('#new-with-date').addEventListener('click',()=>openEditor());
function closeMenu(focus=false){if(!menuTrigger)return;$('#task-menu').hidePopover();const trigger=menuTrigger;trigger.setAttribute('aria-expanded','false');menuTrigger=null;menuId=null;if(focus)trigger.focus();}
function openMenu(task,trigger){if(menuTrigger===trigger){closeMenu(true);return;}closeMenu();menuTrigger=trigger;menuId=task.id;trigger.setAttribute('aria-expanded','true');$('#task-menu [data-action=work]').disabled=task.completedAt!==null;const menu=$('#task-menu');menu.showPopover();const rect=trigger.getBoundingClientRect(),bounds=menu.getBoundingClientRect();menu.style.left=`${Math.max(8,Math.min(rect.right-bounds.width,innerWidth-bounds.width-8))}px`;menu.style.top=`${Math.max(8,Math.min(rect.bottom+4,innerHeight-bounds.height-8))}px`;menu.querySelector('button:not(:disabled)').focus();}
$('#task-menu').addEventListener('click',async event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;const task=state.tasks.find(item=>item.id===menuId);closeMenu();if(!task)return;if(action==='edit'||action==='date'){openEditor(task,action==='date');return;}const row=$$('.task[data-task]').find(node=>node.dataset.task===task.id);if(action==='delete'&&row)animate(row,[{opacity:1},{opacity:.2,transform:'translateX(14px)'}],180);if(await mutate({type:action,id:task.id})){if(action==='delete')$('#undo-delete').focus();else $('#task-input').focus();}});
$('#task-menu').addEventListener('keydown',event=>{const items=$$('#task-menu button:not(:disabled)'),index=items.indexOf(document.activeElement);let target;if(event.key==='ArrowDown')target=(index+1)%items.length;if(event.key==='ArrowUp')target=(index-1+items.length)%items.length;if(event.key==='Home')target=0;if(event.key==='End')target=items.length-1;if(target!==undefined){event.preventDefault();items[target].focus();}if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeMenu(true);}if(event.key==='Tab')closeMenu();});
document.addEventListener('pointerdown',event=>{if(menuTrigger&&!event.target.closest('#task-menu')&&!event.target.closest('.task-more'))closeMenu();});document.addEventListener('scroll',event=>{if(menuTrigger&&!$('#task-menu').contains(event.target))closeMenu();},true);window.addEventListener('resize',()=>closeMenu());
$('#undo-delete').addEventListener('click',()=>{const task=pendingTasks().at(-1);if(task)mutate({type:'undo',id:task.id});});$('#undo-bar').addEventListener('pointerenter',()=>{undoHover=true;renderUndo();});$('#undo-bar').addEventListener('pointerleave',()=>{undoHover=false;renderUndo();});$('#undo-bar').addEventListener('focusin',renderUndo);$('#undo-bar').addEventListener('focusout',()=>queueMicrotask(renderUndo));
$('#pin').addEventListener('click',async()=>{try{const pinned=!(native.pinned??state.settings.pinned);await host.window('pin',{pinned});native.pinned=pinned;await mutate({type:'settings',patch:{pinned}});}catch(error){report(error);}});
$('#drag-handle').addEventListener('pointerdown',event=>{if(event.button===0&&!event.target.closest('button'))host.window('drag').catch(error=>report(error));});
$('#settings-open').addEventListener('click',()=>{const form=$('#settings-form');for(const control of form.elements){if(!control.name)continue;const value=state.settings[control.name];if(control.type==='checkbox')control.checked=!!value;else control.value=String(value??'');}form.elements.autostart.checked=native.autostart??state.settings.autostart;$('#settings-error').hidden=true;openDialog($('#settings'));});
$('#settings-form').addEventListener('submit',async event=>{
  event.preventDefault();if(busy)return;
  const form=event.currentTarget,patch={};
  for(const control of form.elements){if(!control.name)continue;patch[control.name]=control.type==='checkbox'?control.checked:control.name==='archiveDays'?Number(control.value):control.value;}
  const previous={...state.settings,autostart:native.autostart??state.settings.autostart,listShortcut:native.hotkeys?.list??state.settings.listShortcut,quickShortcut:native.hotkeys?.quick??state.settings.quickShortcut};
  setBusy(true);
  try{
    applyCommand(state,{type:'settings',patch},context());
    await saveSettings(host,previous,patch,async()=>{
      setBusy(false);
      try{return await mutate({type:'settings',patch},{errorTarget:$('#settings-error')});}
      finally{setBusy(true);}
    });
    native.autostart=patch.autostart;clearError();closeDialog($('#settings'));
  }catch(error){report(error,null,$('#settings-error'));}
  finally{setBusy(false);if(latestExternal){state=latestExternal.state;revision=latestExternal.revision;latestExternal=null;render();}}
});
$('#hide-widget').addEventListener('click',()=>host.window('hide').catch(error=>report(error)));$('#open-archive').addEventListener('click',()=>openCollection('archive'));$('#open-trash').addEventListener('click',()=>openCollection('trash'));
function openCollection(type){collectionType=type;closeDialog($('#settings'));renderCollection();openDialog($('#collection'));}
function renderCollection(){text($('#collection-title'),t(collectionType));text($('#collection-note'),t(collectionType==='trash'?'trashNote':'archiveNote'));const list=$('#collection-list');list.replaceChildren();const tasks=state.tasks.filter(task=>task.lifecycle===collectionType);if(!tasks.length)list.append(element('p','empty',t('emptyCollection')));for(const task of tasks){const row=element('div','collection-row'),copy=element('span','collection-copy',task.title);copy.append(element('small','',`${task.completedAt!==null?t('completed')+' · ':''}${dateText(task)} · ${formatElapsed(task.elapsedMs)}`));row.append(copy,button('',t('restore'),async()=>{if(task.due&&task.due.at<=Date.now()&&task.completedAt===null&&!confirm(t('restoreLate')))return;await mutate({type:'restore',id:task.id});}));list.append(row);}}
$('#reputation').addEventListener('click',()=>{renderHistory();openDialog($('#history'));});
function renderHistory(){const list=$('#history-list');list.replaceChildren();for(const event of [...state.events].reverse().slice(0,100)){const row=element('div','history-row');const task=state.tasks.find(task=>task.id===event.taskId);row.append(element('strong','',`${event.delta>0?'+':''}${event.delta??0}`),document.createTextNode(task?.title||t('reputation')),element('div','',new Intl.DateTimeFormat(locale,{dateStyle:'short',timeStyle:'short'}).format(new Date(event.at??Date.now()))));list.append(row);}if(!state.events.length)list.append(element('p','empty',t('emptyCollection')));}
$('#retry').addEventListener('click',()=>retryAction?.());$('#error-close').addEventListener('click',clearError);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!event.defaultPrevented&&!$('dialog[open]')){if(menuTrigger){event.preventDefault();closeMenu(true);}else if(quick){const input=$('#task-input');input.value='';grow(input);setBusy(busy);host.window('quickDone').catch(error=>report(error));}else host.window('hide').catch(error=>report(error));}});
host.addEventListener('stateChanged',event=>{const payload=event.detail;if(!payload?.state||payload.revision<=revision)return;try{assertState(payload.state);}catch{return;}if(busy){latestExternal=payload;return;}state=payload.state;revision=payload.revision;render();});
host.addEventListener('nativeChanged',event=>{native={...event.detail};render();});host.addEventListener('visibility',event=>{nativeVisible=event.detail.visible;lastUndo=mono();renderUndo();if(nativeVisible&&quick)$('#task-input').focus();});host.addEventListener('focusQuick',()=>$('#task-input').focus());
async function suspend(finalize=false){if(quick)return;while(busy)await new Promise(resolve=>setTimeout(resolve,25));const saved=await transaction([{type:'suspend'},...(finalize?[{type:'finalizeDeletes'}]:[])],{silent:true});if(finalize)await host.window(saved?'exitReady':'cancelExit');}
host.addEventListener('suspend',()=>suspend().catch(error=>report(error)));host.addEventListener('beforeExit',()=>suspend(true).catch(error=>report(error)));
setInterval(async()=>{const now=mono(),delta=Math.max(0,now-lastUndo);lastUndo=now;if(!state||busy||!ready||quick)return;if(pendingTasks().length){const next=applyCommand(state,{type:'advanceUndo',delta,paused:undoPaused()},context());const expired=next.tasks.some(task=>task.lifecycle==='trash'&&state.tasks.find(old=>old.id===task.id)?.lifecycle==='pending');if(expired){setBusy(true);try{await commitState(next);}catch(error){report(error);}finally{setBusy(false);}}else{state=next;renderUndo();}}if(now-lastTick>=1000){lastTick=now;updateTimes();await mutate({type:'tick'},{silent:true,notifyOverdue:true});}if(now-lastCheckpoint>=5000){lastCheckpoint=now;if(state.tasks.some(task=>task.workState==='running'))await mutate({type:'checkpoint'},{silent:true});}},200);
host.addEventListener('exitFailed',()=>report(Error('saveError')));
localize();load({startup:true}).then(()=>{if(quick)$('#task-input').focus();}).catch(error=>{ready=false;report(error,()=>load({startup:true}));const empty=$('#empty');if(empty)text(empty,t('loadError'));});

$('#restore-backup').addEventListener('click',async()=>{if(busy||!confirm(t('restoreConfirm')))return;setBusy(true);try{await host.request('restoreBackup');await load({startup:true});clearError();}catch(error){ready=false;report(Error('dataCorrupt'));text($('#error-text'),t('restoreFailed'));}finally{setBusy(false);}});
