export const messages={
ru:{loading:'Загрузка…',newTask:'Новая задача',placeholder:'Что нужно сделать?',pin:'Закрепить поверх окон',unpin:'Вернуть на рабочий стол',settings:'Настройки',reputation:'Репутация',close:'Закрыть',retry:'Повторить',add:'Добавить задачу',date:'Срок',time:'Время (необязательно)',today:'Сегодня',tomorrow:'Завтра',noDate:'Без срока',taskTitle:'Текст задачи',enterHint:'Enter — сохранить · Shift + Enter — новая строка',save:'Сохранить',edit:'Редактировать',work:'В работу без таймера',delete:'Удалить',actions:'Действия с задачей',language:'Язык',theme:'Тема',system:'Как в Windows',light:'Светлая',dark:'Тёмная',completionSound:'Звук выполнения',overdueSound:'Звук просрочки',reducedMotion:'Уменьшить движение',autostart:'Запускать при входе в Windows',autoArchive:'Автоархив незавершённых',all:'Все задачи',dated:'Только со сроком',undated:'Только без срока',off:'Выключен',archiveDays:'Через сколько дней',listShortcut:'Показать список',quickShortcut:'Быстрый ввод',archive:'Архив',trash:'Корзина',hide:'Скрыть в трей',undo:'Отменить',empty:'Пока нет задач. Начните с одного дела.',late:'Просрочено',upcoming:'Ближайшие',any:'Без срока',done:'Готово сегодня',complete:'Выполнить',uncomplete:'Отменить выполнение',start:'Запустить секундомер',pause:'Приостановить',stop:'Закончить подход',running:'В работе',paused:'На паузе',working:'В работе без таймера',idle:'Затрачено',completed:'Готово',restore:'Восстановить',archiveNote:'Восстановленные задачи вернутся в список.',trashNote:'Задачи хранятся 30 дней с момента удаления, затем удаляются окончательно.',emptyCollection:'Здесь пока пусто',restoreLate:'Срок уже прошёл. Восстановить задачу? Неучтённые штрафы будут применены.',undoHint:'Затем в корзину',undoPaused:'Отсчёт приостановлен',moreDeleted:'ещё',saved:'Сохранено',saveError:'Не удалось сохранить. Ваш текст сохранён в поле; повторите попытку.',loadError:'Не удалось открыть данные. Они не были заменены.',conflict:'Данные изменились в другом окне. Обновлены; повторите действие.',nativeError:'Не удалось применить настройку Windows. Проверьте сочетания клавиш и повторите.',invalidDate:'Проверьте дату и время. Для времени нужна дата.',noHost:'Откройте Delo через установленное приложение. Нативное хранилище недоступно.',reputationHint:'Выполнение: +5, после срока: +2. Просрочка: −2, через 7 дней: ещё −1. Отмена снимает награду.',deadlineZone:'Часовой пояс',dueNone:'Без срока',reward:'Выполнение',penalty:'Просрочка',reversal:'Отмена выполнения'},
uk:{loading:'Завантаження…',newTask:'Нове завдання',placeholder:'Що потрібно зробити?',pin:'Закріпити поверх вікон',unpin:'Повернути на робочий стіл',settings:'Налаштування',reputation:'Репутація',close:'Закрити',retry:'Повторити',add:'Додати завдання',date:'Термін',time:'Час (необов’язково)',today:'Сьогодні',tomorrow:'Завтра',noDate:'Без терміну',taskTitle:'Текст завдання',enterHint:'Enter — зберегти · Shift + Enter — новий рядок',save:'Зберегти',edit:'Редагувати',work:'У роботу без таймера',delete:'Видалити',actions:'Дії із завданням',language:'Мова',theme:'Тема',system:'Як у Windows',light:'Світла',dark:'Темна',completionSound:'Звук виконання',overdueSound:'Звук прострочення',reducedMotion:'Зменшити рух',autostart:'Запускати під час входу у Windows',autoArchive:'Автоархів незавершених',all:'Усі завдання',dated:'Лише з терміном',undated:'Лише без терміну',off:'Вимкнено',archiveDays:'Через скільки днів',listShortcut:'Показати список',quickShortcut:'Швидке введення',archive:'Архів',trash:'Кошик',hide:'Сховати в трей',undo:'Скасувати',empty:'Поки немає завдань. Почніть з однієї справи.',late:'Прострочено',upcoming:'Найближчі',any:'Без терміну',done:'Виконано сьогодні',complete:'Виконати',uncomplete:'Скасувати виконання',start:'Запустити секундомір',pause:'Призупинити',stop:'Закінчити підхід',running:'У роботі',paused:'На паузі',working:'У роботі без таймера',idle:'Витрачено',completed:'Готово',restore:'Відновити',archiveNote:'Відновлені завдання повернуться до списку.',trashNote:'Завдання зберігаються 30 днів від видалення, потім видаляються назавжди.',emptyCollection:'Тут поки порожньо',restoreLate:'Термін уже минув. Відновити завдання? Невраховані штрафи буде застосовано.',undoHint:'Потім у кошик',undoPaused:'Відлік призупинено',moreDeleted:'ще',saved:'Збережено',saveError:'Не вдалося зберегти. Ваш текст залишився в полі; повторіть спробу.',loadError:'Не вдалося відкрити дані. Їх не було замінено.',conflict:'Дані змінилися в іншому вікні. Оновлено; повторіть дію.',nativeError:'Не вдалося застосувати налаштування Windows. Перевірте сполучення клавіш.',invalidDate:'Перевірте дату й час. Для часу потрібна дата.',noHost:'Відкрийте Delo через установлену програму. Нативне сховище недоступне.',reputationHint:'Виконання: +5, після терміну: +2. Прострочення: −2, через 7 днів: ще −1. Скасування знімає нагороду.',deadlineZone:'Часовий пояс',dueNone:'Без терміну',reward:'Виконання',penalty:'Прострочення',reversal:'Скасування виконання'},
en:{loading:'Loading…',newTask:'New task',placeholder:'What needs doing?',pin:'Keep above windows',unpin:'Return to desktop',settings:'Settings',reputation:'Reputation',close:'Close',retry:'Retry',add:'Add task',date:'Due date',time:'Time (optional)',today:'Today',tomorrow:'Tomorrow',noDate:'No due date',taskTitle:'Task text',enterHint:'Enter to save · Shift + Enter for a new line',save:'Save',edit:'Edit',work:'Work without timer',delete:'Delete',actions:'Task actions',language:'Language',theme:'Theme',system:'Follow Windows',light:'Light',dark:'Dark',completionSound:'Completion sound',overdueSound:'Overdue sound',reducedMotion:'Reduce motion',autostart:'Start when signing in to Windows',autoArchive:'Auto-archive unfinished tasks',all:'All tasks',dated:'Only with a due date',undated:'Only without a due date',off:'Off',archiveDays:'After this many days',listShortcut:'Show task list',quickShortcut:'Quick entry',archive:'Archive',trash:'Trash',hide:'Hide to tray',undo:'Undo',empty:'No tasks yet. Start with one thing.',late:'Overdue',upcoming:'Upcoming',any:'No due date',done:'Completed today',complete:'Complete',uncomplete:'Undo completion',start:'Start timer',pause:'Pause timer',stop:'End session',running:'Working',paused:'Paused',working:'Working without timer',idle:'Time spent',completed:'Done',restore:'Restore',archiveNote:'Restored tasks return to your list.',trashNote:'Tasks are kept for 30 days after deletion, then permanently removed.',emptyCollection:'Nothing here yet',restoreLate:'The due date has passed. Restore this task? Outstanding penalties will be applied.',undoHint:'Then moved to trash',undoPaused:'Countdown paused',moreDeleted:'more',saved:'Saved',saveError:'Could not save. Your text remains in the field; please retry.',loadError:'Could not open your data. It has not been replaced.',conflict:'Data changed in another window. Refreshed; please try again.',nativeError:'Could not apply Windows settings. Check the shortcuts and retry.',invalidDate:'Check the date and time. A time requires a date.',noHost:'Open Delo through the installed application. Native storage is unavailable.',reputationHint:'Complete: +5, late: +2. Overdue: −2, after 7 days: another −1. Undo removes the reward.',deadlineZone:'Time zone',dueNone:'No due date',reward:'Completion',penalty:'Overdue',reversal:'Completion undone'}
};
Object.assign(messages.ru,{restoreBackup:'Восстановить резервную копию',dataCorrupt:'Данные повреждены. Сохранение остановлено. Можно восстановить предыдущую резервную копию; исходный файл останется сохранён.',restoreConfirm:'Восстановить предыдущую резервную копию? Изменения после её создания могут отсутствовать. Текущий файл будет сохранён отдельно.',restoreFailed:'Не удалось восстановить резервную копию. Исходные данные не заменены.'});
Object.assign(messages.uk,{restoreBackup:'Відновити резервну копію',dataCorrupt:'Дані пошкоджені. Збереження зупинено. Можна відновити попередню резервну копію; вихідний файл буде збережено.',restoreConfirm:'Відновити попередню резервну копію? Змін після її створення може не бути. Поточний файл буде збережено окремо.',restoreFailed:'Не вдалося відновити резервну копію. Вихідні дані не замінено.'});
Object.assign(messages.en,{restoreBackup:'Restore backup',dataCorrupt:'Data is damaged. Saving has stopped. You can restore the previous backup; the original file will be preserved.',restoreConfirm:'Restore the previous backup? Changes made since it was created may be missing. The current file will be preserved separately.',restoreFailed:'The backup could not be restored. Original data was not replaced.'});
export function translator(language){const dictionary=messages[language]||messages.ru;return key=>dictionary[key]||messages.en[key]||key;}
messages.ru.hotkeyError='Не удалось включить горячие клавиши: сочетание занято или задано неверно. Откройте настройки и выберите разные сочетания Ctrl/Alt/Shift/Win с буквой, цифрой или Space.';
messages.uk.hotkeyError='Не вдалося ввімкнути гарячі клавіші: комбінація зайнята або неправильна. Відкрийте налаштування й виберіть різні комбінації Ctrl/Alt/Shift/Win з літерою, цифрою або Space.';
messages.en.hotkeyError='Shortcuts could not be enabled: a combination is in use or invalid. Open Settings and choose different Ctrl/Alt/Shift/Win combinations with a letter, digit or Space.';
messages.ru.nativeRollbackError='Не удалось вернуть системные настройки после ошибки сохранения. Проверьте горячие клавиши и автозапуск.';
messages.uk.nativeRollbackError='Не вдалося повернути системні налаштування після помилки збереження. Перевірте гарячі клавіші й автозапуск.';
messages.en.nativeRollbackError='System settings could not be restored after a save error. Check shortcuts and startup settings.';
messages.ru.voice='Голосовой ввод — скоро';
messages.uk.voice='Голосове введення — незабаром';
messages.en.voice='Voice input — coming soon';
export const localeFor=language=>({ru:'ru-RU',uk:'uk-UA',en:'en-GB'}[language]||'ru-RU');
