import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,applyCommand,makeDeadline,DAY,validateState,recoverState,elapsed,formatElapsed,groups} from '../core/model.mjs';
const base=Date.parse('2026-01-01T12:00Z');
const run=(s,c,now=base,monotonic=0)=>applyCommand(s,c,{now,monotonic,timeZone:'UTC'});
const add=(s,id,due)=>run(s,{type:'create',id,title:id,due});
test('V03 invalid edit and date leave original state untouched',()=>{let s=add(createState(),'a');const copy=JSON.stringify(s);assert.throws(()=>run(s,{type:'edit',id:'a',title:'  '}));assert.equal(JSON.stringify(s),copy);for(const date of ['2026-02-29','2026-13-01','2026-04-31'])assert.throws(()=>makeDeadline(date));assert.throws(()=>makeDeadline('2026-01-01','24:00'));assert.equal(validateState(s).valid,true);});
test('V05 monotonic timer, single runner, pause resume stop and completion',()=>{let s=add(add(createState(),'a'),'b');s=run(s,{type:'start',id:'a'},base,100);s=run(s,{type:'pause',id:'a'},base-10000,1100);assert.equal(s.tasks[0].elapsedMs,1000);s=run(s,{type:'start',id:'a'},base,2100);s=run(s,{type:'start',id:'b'},base,3100);assert.equal(s.tasks[0].elapsedMs,2000);assert.equal(s.tasks[0].workState,'paused');s=run(s,{type:'stop',id:'b'},base,4100);s=run(s,{type:'start',id:'b'},base,5100);s=run(s,{type:'complete',id:'b'},base,6100);assert.equal(s.tasks[1].elapsedMs,2000);assert.equal(s.reputation,5);assert.equal(formatElapsed(25*3600000),'25:00:00');assert.equal(validateState(s).valid,true);});
test('V06 penalties, negative reputation, late completion and undo survive restart',()=>{let s=add(createState(),'a',makeDeadline('2026-01-01','13:00'));const due=s.tasks[0].due.at;s=run(s,{type:'tick'},due);assert.equal(s.reputation,-2);s=run(s,{type:'tick'},due+7*DAY);assert.equal(s.reputation,-3);s=run(s,{type:'complete',id:'a'},due+7*DAY);assert.equal(s.reputation,-1);s=run(s,{type:'complete',id:'a'},due+7*DAY);assert.equal(s.reputation,-1);s=run(recoverState(s),{type:'uncomplete',id:'a'},due+7*DAY);assert.equal(s.reputation,-3);s=run(s,{type:'complete',id:'a'},due+7*DAY);assert.equal(s.reputation,-1);assert.equal(s.events.filter(e=>e.kind==='first').length,1);assert.equal(validateState(s).valid,true);});
test('V07 fixed-zone midnight and DST boundaries',()=>{const due=makeDeadline('2026-03-29','','Europe/Berlin');assert.equal(new Date(due.at).toISOString(),'2026-03-29T22:00:00.000Z');assert.throws(()=>makeDeadline('2026-03-29','02:30','Europe/Berlin'));assert.equal(new Date(makeDeadline('2026-10-25','02:30','Europe/Berlin').at).toISOString(),'2026-10-25T00:30:00.000Z');let s=add(createState(),'a',makeDeadline('2026-01-01'));s=run(s,{type:'tick'},s.tasks[0].due.at-1);assert.equal(s.reputation,0);s=applyCommand(s,{type:'tick'},{now:s.tasks[0].due.at,monotonic:0,timeZone:'America/New_York'});assert.equal(s.reputation,-2);});
test('V07 changed deadline keeps paid penalties and moves unpaid week event',()=>{let s=add(createState(),'a',makeDeadline('2026-01-01','13:00'));s=run(s,{type:'tick'},base+3600000);s=run(s,{type:'deadline',id:'a',due:makeDeadline('2026-01-10')},base+3600000);s=run(s,{type:'tick'},base+8*DAY);assert.equal(s.reputation,-2);s=run(s,{type:'tick'},Date.parse('2026-01-18T00:00Z'));assert.equal(s.reputation,-3);s=run(s,{type:'deadline',id:'a',due:null},Date.parse('2026-01-18T00:00Z'));assert.equal(s.reputation,-3);});
test('V08 offline ordering: archive stops later penalties; tie penalizes before archive',()=>{let s=run(createState(),{type:'settings',patch:{archiveDays:1}});s=add(s,'later',makeDeadline('2026-01-03','12:00'));s=add(s,'earlier',makeDeadline('2026-01-02','12:00'));s=run(s,{type:'tick'},base+20*DAY);assert.deepEqual(s.events.map(e=>[e.taskId,e.kind]),[['earlier','first'],['later','first']]);assert.equal(s.reputation,-4);assert.ok(s.tasks.every(t=>t.lifecycle==='archive'));});
test('V08 scopes, future protection, restored age and completed restore day',()=>{for(const scope of ['all','dated','undated','off']){let s=run(createState(),{type:'settings',patch:{archiveDays:1,autoArchive:scope}});s=add(add(s,'plain'),'due',makeDeadline('2026-01-04'));s=run(s,{type:'tick'},base+2*DAY);assert.equal(s.tasks[0].lifecycle,['all','undated'].includes(scope)?'archive':'active');assert.equal(s.tasks[1].lifecycle,'active');}let s=add(createState(),'a');s=run(s,{type:'tick'},base+31*DAY);s=run(s,{type:'restore',id:'a'},base+31*DAY);s=run(s,{type:'tick'},base+60*DAY);assert.equal(s.tasks[0].lifecycle,'active');s=run(s,{type:'tick'},base+61*DAY);assert.equal(s.tasks[0].lifecycle,'archive');s=run(s,{type:'restore',id:'a'},base+62*DAY);s=run(s,{type:'complete',id:'a'},base+62*DAY);s=run(s,{type:'tick'},base+63*DAY);s=run(s,{type:'restore',id:'a'},base+64*DAY);assert.equal(s.reputation,5);assert.equal(s.tasks[0].lifecycle,'active');s=run(s,{type:'tick'},base+65*DAY);assert.equal(s.tasks[0].lifecycle,'archive');});
test('V09 independent undo clocks, paused UI, latest deletion, restart and retention boundary',()=>{let s=add(add(run(createState(),{type:'settings',patch:{autoArchive:'off'}}),'a'),'b');s=run(s,{type:'delete',id:'b'});s=run(s,{type:'advanceUndo',delta:2000});s=run(s,{type:'delete',id:'a'},base+1);s=run(s,{type:'advanceUndo',delta:5000,paused:true});assert.equal(s.tasks[1].undoRemaining,3000);s=run(s,{type:'undo'},base+2);assert.equal(s.tasks[0].lifecycle,'active');s=run(s,{type:'advanceUndo',delta:3000},base+3000);assert.equal(s.tasks[1].lifecycle,'trash');s=run(s,{type:'tick'},base+30*DAY-1);assert.equal(s.tasks.length,2);s=run(s,{type:'tick'},base+30*DAY);assert.equal(s.tasks.some(t=>t.id==='b'),false);s=run(s,{type:'delete',id:'a'},base+30*DAY);s=recoverState(s);assert.equal(s.tasks[0].lifecycle,'trash');});
test('manual lifecycle is active to archive to trash to permanent deletion',()=>{let s=add(add(run(createState(),{type:'settings',patch:{autoArchive:'off'}}),'a'),'b');s=run(s,{type:'start',id:'a'},base,100);s=run(s,{type:'archive',id:'a'},base+1,1100);assert.equal(s.tasks[0].lifecycle,'archive');assert.equal(s.tasks[0].workState,'paused');assert.equal(s.tasks[0].elapsedMs,1000);assert.throws(()=>run(s,{type:'trash',id:'b'}),/archived/);s=run(s,{type:'trash',id:'a'},base+2,1200);assert.equal(s.tasks[0].lifecycle,'trash');assert.equal(s.tasks[0].deletedAt,base+2);s=run(s,{type:'purge',id:'a'},base+3,1300);assert.deepEqual(s.tasks.map(task=>task.id),['b']);s=run(s,{type:'archive',id:'b'},base+4,1400);s=run(s,{type:'trash',id:'b'},base+5,1500);s=run(s,{type:'clearTrash'},base+6,1600);assert.equal(s.tasks.length,0);assert.equal(validateState(s).valid,true);});
test('V11 recovery preserves saved accumulation, rejects corruption',()=>{let s=add(createState(),'a');s=run(s,{type:'start',id:'a'},base,0);s=run(s,{type:'checkpoint'},base,2500);assert.equal(elapsed(s.tasks[0],3000),3000);let recovered=recoverState(JSON.parse(JSON.stringify(s)));assert.equal(recovered.tasks[0].workState,'paused');assert.equal(recovered.tasks[0].elapsedMs,2500);s.reputation=100;assert.throws(()=>recoverState(s));assert.equal(groups(recovered,{now:base,timeZone:'UTC'})[0].key,'any');});
test('V05 work without timer and deletion preserve accumulation without auto-resume',()=>{let s=add(createState(),'a');s=run(s,{type:'start',id:'a'},base,0);s=run(s,{type:'work',id:'a'},base,1500);assert.equal(elapsed(s.tasks[0],99999),1500);assert.equal(s.reputation,0);s=run(s,{type:'start',id:'a'},base,2000);s=run(s,{type:'delete',id:'a'},base,2500);s=run(s,{type:'undo'},base,3000);assert.equal(s.tasks[0].workState,'paused');assert.equal(s.tasks[0].elapsedMs,2000);assert.equal(s.reputation,0);});
test('V06 no deadline and in-time rewards, restoration evaluates only missing penalties',()=>{let s=add(add(createState(),'plain'),'dated',makeDeadline('2026-01-02'));s=run(s,{type:'complete',id:'plain'});s=run(s,{type:'complete',id:'dated'});assert.equal(s.reputation,10);s=add(s,'old',makeDeadline('2026-01-01','13:00'));s=run(s,{type:'delete',id:'old'});s=run(s,{type:'finalizeDeletes'});s=run(s,{type:'restore',id:'old'},base+8*DAY);assert.equal(s.reputation,7);s=run(s,{type:'tick'},base+8*DAY);assert.equal(s.reputation,7);assert.equal(validateState(s).valid,true);});
const deleteEvent=event=>({type:'deleteEvent',eventId:event.id,taskId:event.taskId,kind:event.kind,at:event.at,delta:event.delta});
test('R04 deleting reputation entries reverses either sign and persists paid penalties',()=>{let positive=add(createState(),'positive');positive=run(positive,{type:'complete',id:'positive'});assert.equal(positive.reputation,5);positive=run(positive,deleteEvent(positive.events[0]));assert.equal(positive.reputation,0);assert.deepEqual(positive.events,[]);let negative=add(createState(),'negative',makeDeadline('2026-01-01','13:00'));negative=run(negative,{type:'tick'},negative.tasks[0].due.at);assert.equal(negative.reputation,-2);negative=run(negative,deleteEvent(negative.events[0]),negative.tasks[0].due.at+1);assert.equal(negative.reputation,0);assert.equal(negative.tasks[0].penalties.first,true);negative=run(recoverState(negative),{type:'tick'},negative.tasks[0].due.at+DAY);assert.equal(negative.reputation,0);assert.deepEqual(negative.events,[]);assert.equal(validateState(negative).valid,true);});
test('R04 deleting a middle event compacts ids and rejects stale identity atomically',()=>{let s=add(add(createState(),'a'),'b');s=run(s,{type:'complete',id:'a'});s=run(s,{type:'complete',id:'b'},base+1);s=run(s,{type:'uncomplete',id:'a'},base+2);s=run(s,deleteEvent(s.events[1]),base+3);assert.deepEqual(s.events.map(event=>[event.id,event.taskId,event.delta]),[[1,'a',5],[2,'a',-5]]);assert.equal(s.reputation,0);const before=JSON.stringify(s);assert.throws(()=>run(s,{...deleteEvent(s.events[0]),taskId:'stale'},base+4),/Unknown event/);assert.equal(JSON.stringify(s),before);});
test('R04 uncomplete compensates only the current completion still present in the ledger',()=>{let normal=add(createState(),'normal');normal=run(normal,{type:'complete',id:'normal'});normal=run(normal,{type:'uncomplete',id:'normal'},base+1);assert.equal(normal.reputation,0);assert.deepEqual(normal.events.map(event=>event.kind),['complete','uncomplete']);let removed=add(createState(),'removed');removed=run(removed,{type:'complete',id:'removed'});removed=run(removed,deleteEvent(removed.events.at(-1)),base+1);removed=run(removed,{type:'uncomplete',id:'removed'},base+2);assert.equal(removed.reputation,0);assert.deepEqual(removed.events,[]);assert.equal(removed.tasks[0].completedAt,null);let cycled=add(createState(),'cycled');cycled=run(cycled,{type:'complete',id:'cycled'});cycled=run(cycled,{type:'uncomplete',id:'cycled'},base+1);cycled=run(cycled,{type:'complete',id:'cycled'},base+2);cycled=run(cycled,deleteEvent(cycled.events[0]),base+3);cycled=run(cycled,{type:'uncomplete',id:'cycled'},base+4);assert.equal(cycled.reputation,-5);assert.deepEqual(cycled.events.map(event=>event.kind),['uncomplete','complete','uncomplete']);assert.equal(validateState(cycled).valid,true);});
test('F06 a pinned task leads the list in pin order and keeps its timer and deadline',()=>{let s=add(add(add(createState(),'old'),'dated',makeDeadline('2026-01-01','13:00')),'new');s=run(s,{type:'start',id:'new'},base,100);s=run(s,{type:'pin',id:'new'},base+1,200);s=run(s,{type:'pin',id:'dated'},base+2,300);s=run(s,{type:'pin',id:'dated'},base+9,400);const g=groups(s,{now:base+3,timeZone:'UTC'});assert.deepEqual(g.map(group=>group.key),['pinned','any']);assert.deepEqual(g[0].tasks.map(task=>task.id),['new','dated']);assert.equal(s.tasks.find(task=>task.id==='dated').pinnedAt,base+2);assert.equal(s.tasks.find(task=>task.id==='new').workState,'running');assert.equal(elapsed(s.tasks.find(task=>task.id==='new'),1100),1000);assert.equal(validateState(s).valid,true);s=run(s,{type:'tick'},Date.parse('2026-01-01T13:00Z'),500);assert.equal(s.reputation,-2);assert.equal(groups(s,{now:Date.parse('2026-01-01T13:00Z'),timeZone:'UTC'})[0].tasks.length,2);});
test('F06 unpin returns the task to its group; completion and restoration clear the pin',()=>{let s=add(add(run(createState(),{type:'settings',patch:{autoArchive:'off'}}),'a'),'b');s=run(s,{type:'pin',id:'b'},base+1);s=run(s,{type:'unpin',id:'b'},base+2);assert.equal('pinnedAt' in s.tasks[1],false);assert.deepEqual(groups(s,{now:base+3,timeZone:'UTC'}).map(group=>group.key),['any']);s=run(s,{type:'pin',id:'a'},base+4);s=run(s,{type:'complete',id:'a'},base+5);assert.equal('pinnedAt' in s.tasks[0],false);assert.throws(()=>run(s,{type:'pin',id:'a'},base+6),/completed/);s=run(s,{type:'uncomplete',id:'a'},base+6);s=run(s,{type:'pin',id:'b'},base+7);s=run(s,{type:'archive',id:'b'},base+8);assert.equal(s.tasks[1].pinnedAt,base+7);s=run(s,{type:'restore',id:'b'},base+9);assert.equal('pinnedAt' in s.tasks[1],false);s=run(s,{type:'pin',id:'b'},base+10);s=run(s,{type:'delete',id:'b'},base+11);s=run(s,{type:'undo'},base+12);assert.equal(s.tasks[1].pinnedAt,base+10);assert.equal(validateState(s).valid,true);});
test('F06 data without pins loads as it is; a broken pin is rejected',()=>{let s=add(createState(),'a');assert.equal('pinnedAt' in s.tasks[0],false);assert.equal(validateState(s).valid,true);const nulled=structuredClone(s);nulled.tasks[0].pinnedAt=null;assert.equal(validateState(nulled).valid,true);for(const value of [-1,'1',Infinity]){const broken=structuredClone(s);broken.tasks[0].pinnedAt=value;assert.equal(validateState(broken).valid,false);}});
test('V30 a new task enters its group at the top; a nearer deadline still leads',()=>{
  const day=Date.parse('2026-01-01T09:00Z'),at=(s,command,ms)=>run(s,command,day+ms);
  let s=createState();
  s=at(s,{type:'create',id:'undated-1',title:'A'},0);s=at(s,{type:'create',id:'undated-2',title:'B'},1000);s=at(s,{type:'create',id:'undated-3',title:'C'},2000);
  s=at(s,{type:'create',id:'today-1',title:'D',due:{date:'2026-01-01',time:'',timeZone:'UTC'}},3000);
  s=at(s,{type:'create',id:'today-2',title:'E',due:{date:'2026-01-01',time:'',timeZone:'UTC'}},4000);
  s=at(s,{type:'create',id:'today-timed',title:'F',due:{date:'2026-01-01',time:'18:00',timeZone:'UTC'}},5000);
  s=at(s,{type:'create',id:'later-1',title:'G',due:{date:'2026-01-05',time:'',timeZone:'UTC'}},6000);
  s=at(s,{type:'create',id:'later-2',title:'H',due:{date:'2026-01-05',time:'',timeZone:'UTC'}},7000);
  s=at(s,{type:'create',id:'sooner',title:'I',due:{date:'2026-01-03',time:'',timeZone:'UTC'}},8000);
  const g=Object.fromEntries(groups(s,{now:day+9000,timeZone:'UTC'}).map(group=>[group.key,group.tasks.map(task=>task.id)]));
  assert.deepEqual(g.any,['undated-3','undated-2','undated-1']);
  // Same day: the timed task is more urgent than date-only ones, then the newest date-only task first.
  assert.deepEqual(g.today,['today-timed','today-2','today-1']);
  // A later-created task with a nearer deadline goes above earlier ones; equal deadlines: newest first.
  assert.deepEqual(g.upcoming,['sooner','later-2','later-1']);
});
test('V31 without a deadline, tasks in work lead: running, then by latest touch, then the rest newest first',()=>{
  const M=60000,at=(s,command,minutes)=>run(s,command,base+minutes*M,minutes*M);
  let s=createState();for(let i=1;i<=50;i++)s=at(s,{type:'create',id:`t${i}`,title:`T${i}`},i/100);
  s=at(s,{type:'create',id:'dated',title:'D',due:{date:'2026-01-03',time:'',timeZone:'UTC'}},1);
  const any=minutes=>groups(s,{now:base+minutes*M,timeZone:'UTC'}).find(group=>group.key==='any').tasks.map(task=>task.id);
  assert.deepEqual(any(1).slice(0,3),['t50','t49','t48']);
  // The 50th from the top starts: it leads, and stays near the top when paused.
  s=at(s,{type:'start',id:'t1'},2);assert.deepEqual(any(2).slice(0,2),['t1','t50']);
  s=at(s,{type:'pause',id:'t1'},10);assert.deepEqual(any(10).slice(0,2),['t1','t50']);
  // Marked in work without a timer, then another one runs: running first, then the latest touch.
  s=at(s,{type:'work',id:'t20'},11);assert.deepEqual(any(11).slice(0,3),['t20','t1','t50']);
  s=at(s,{type:'start',id:'t30'},12);assert.deepEqual(any(12).slice(0,4),['t30','t20','t1','t50']);
  // Starting another pauses the running one at that moment: it ran last, so it comes next.
  s=at(s,{type:'start',id:'t1'},20);assert.deepEqual(any(20).slice(0,4),['t1','t30','t20','t50']);
  // A task with a deadline keeps the deadline order and its group.
  s=at(s,{type:'start',id:'dated'},21);assert.equal(groups(s,{now:base+21*M,timeZone:'UTC'}).find(group=>group.key==='upcoming').tasks[0].id,'dated');
  assert.deepEqual(any(21).slice(0,4),['t1','t30','t20','t50']);
  // Stopping and completing take a task out of work.
  s=at(s,{type:'stop',id:'t1'},22);s=at(s,{type:'complete',id:'t30'},23);
  assert.deepEqual(any(23).slice(0,2),['t20','t50']);assert.equal(any(23).at(-1),'t1');
  assert.equal(validateState(s).valid,true);
});
test('V31 data without touchedAt loads; old paused tasks rank by their last run; a broken touch is rejected',()=>{
  let s=add(add(add(createState(),'a'),'b'),'c');
  s=run(s,{type:'start',id:'a'},base+1000,0);s=run(s,{type:'start',id:'b'},base+5000,4000);s=run(s,{type:'pause',id:'b'},base+9000,8000);
  const old=structuredClone(s);for(const task of old.tasks)delete task.touchedAt;
  assert.equal(validateState(old).valid,true);
  assert.deepEqual(groups(old,{now:base+9000,timeZone:'UTC'})[0].tasks.map(task=>task.id),['b','a','c']);
  for(const value of [-1,'1',Infinity,null]){const broken=structuredClone(s);broken.tasks[0].touchedAt=value;assert.equal(validateState(broken).valid,false);}
});
